[workspace]
members = [ 
	"assembly-dereference",
	"coroutine",
	"coroutines-variables",
	"epoll",
	"examples",
	"mrapps",
	"os-threds",
	"raw-syscall",
	"runtime",
	"runtime-executor",
]
resolver = "2"

